version: '3'
services:
  postgres:
    container_name: postgres-monmon
    image: postgres:11
    environment:
      - HOSTNAME=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:12.0.2
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_SCHEMA=public
      - DB_PASSWORD=docker
    ports:
      - 8080:8080
    restart: always

volumes:
  db-data:
    driver: local